CA_ATaleOfThreeCalculators/Controllers/FormCalculatorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CA_ATaleOfThreeCalculators.Controllers
{
    public class FormCalculatorController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Calculate(string operation, string operand1, string operand2)
        {
            double operand1Num;
            double operand2Num;
            List<string> errorMessageText = new List<string>();
            ViewBag.errorMessage = null;
            ViewBag.answer = null;

            if ((double.TryParse(operand1, out operand1Num)) && (double.TryParse(operand2, out operand2Num)))
            {
                switch (operation)
                {
                    case "add":
                        {
                            ViewBag.answer = operand1Num + operand2Num;
                            break;
                        }
                    case "subtract":
                        {
                            ViewBag.answer = operand1Num - operand2Num;
                            break;
                        }
                    case "multiply":
                        {
                            ViewBag.answer = operand1Num * operand2Num;
                            break;
                        }
                    case "divide":
                        {
                            if (operand2Num != 0)
                            {
                                ViewBag.answer = operand1Num / operand2Num;
                            }
                            else
                            {
                                errorMessageText.Add("It appears that you are dividing by zero.");
                                errorMessageText.Add("Please click the Try Again button below to reenter your numbers.");
                            }
                            break;
                        }
                    default:
                        errorMessageText.Add("It appears that you did not enter valid operation.");
                        errorMessageText.Add("Please click the Try Again button below to reenter your numbers.");
                        break;
                }
            }
            else
            {
                errorMessageText.Add("It appears that you did not enter valid numbers.");
                errorMessageText.Add("Please click the Try Again button below to reenter your numbers.");
            }

            ViewBag.errorMessage = errorMessageText;

            return View();
        }
    }
}

CA_ATaleOfThreeCalculators/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CA_ATaleOfThreeCalculators.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
    }
}

CA_ATaleOfThreeCalculators/Controllers/TableGeneratorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CA_ATaleOfThreeCalculators.Controllers
{
    public class TableGeneratorController : Controller
    {
        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Index(string temperature, string windSpeed)
        {
            double temperatureNum;
            double windSpeedNum;
            List<string> errorMessageText = new List<string>();
            ViewBag.errorMessage = null;

            if (!(double.TryParse(temperature, out temperatureNum)) || !(double.TryParse(windSpeed, out windSpeedNum)))
            {
                errorMessageText.Add("It appears that you did not enter valid numbers.");
                errorMessageText.Add("Please click the Try Again button below to reenter your numbers.");
            }
            else
            {
                ViewBag.Temperature = temperatureNum;
                ViewBag.WindSpeed = windSpeedNum;
            }

            ViewBag.errorMessage = errorMessageText;

            return View("DisplayTable");
        }
    }
}

CA_ATaleOfThreeCalculators/Controllers/UrlCalculatorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CA_ATaleOfThreeCalculators.Controllers
{
    public class UrlCalculatorController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Add(string operand1, string operand2)
        {
            double operand1Num;
            double operand2Num;
            List<string> errorMessageText = new List<string>();
            ViewBag.errorMessage = null;

            if (double.TryParse(operand1, out operand1Num) && double.TryParse(operand2, out operand2Num))
            {
                ViewBag.answer = (operand1 + operand2).ToString();
            }
            else
            {
                errorMessageText.Add("It appears that you did not enter valid operation.");
                errorMessageText.Add("Please click the Try Again button below to reenter your numbers.");
                ViewBag.errorMessage = errorMessageText;
            }

            return View();
        }
    }
}

CA_ATaleOfThreeCalculators/Views/FormCalculator/Calculate.cshtml
<h2>Calculate</h2>

<div id="CalculatorOutput">

    @if (ViewBag.answer != null)
    {
        <p>Answer = @ViewBag.answer</p>
    }
    else
    {
        foreach(string errorMessageLine in @ViewBag.errorMessage)
        {
            <p>@errorMessageLine</p>
        }
    }

    @Html.ActionLink("Try Again", "Index", "FormCalculator", null, new { @class = "btn btn-default" })

</div>

CA_ATaleOfThreeCalculators/Views/FormCalculator/Index.cshtml
<h2>Form Calculator</h2>

<form action="FormCalculator/Calculate" method="Post" id="CalculatorInputForm">

    <div class="form-group">
        <label for="operand1">Enter the first operand:</label>
        <input type="text" name="operand1" class="form-control" />
    </div>

    <div class="form-group">
        <label for="operand2">Enter the second operand:</label>
        <input type="text" name="operand2" class="form-control" />
    </div>

    <div class="form-group">
        <label for="operation">Choose the operation:</label>
        <select name="operation" class="form-control">
            <option value="add">Add</option>
            <option value="subtract">Subtract</option>
            <option value="multiply">Multiply</option>
            <option value="divide">Divide</option>
        </select>
    </div>

    <div class="form-group">
        <input type="submit" name="submit" value="Calculate" class="btn btn-default" />
    </div>

</form>

CA_ATaleOfThreeCalculators/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

CA_ATaleOfThreeCalculators/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

CA_ATaleOfThreeCalculators/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>A Tale of Three Calculators</h1>
</div>

<div class="row">
    <div class="col-md-12">
        <h2>Description</h2>
        <p>
            The focus of this activity is to develop an application that explores the basic routing and form usage of the ASP.NET MVC framework. The student will develop three calculators, one that uses the URL to provide the operands for a calculator, another that uses a form, and a third that explores the use of Action Verbs in the controller.
        </p>
    </div>
</div>

CA_ATaleOfThreeCalculators/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>A Tale of Three Calculators</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("A Tale of Three Calculators", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("URL Calculator", "Index", "UrlCalculator")</li>
                    <li>@Html.ActionLink("Form Calculator", "Index", "FormCalculator")</li>
                    <li>@Html.ActionLink("Table Generator", "Index", "TableGenerator")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Laughing Leaf Productions</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

CA_ATaleOfThreeCalculators/Views/TableGenerator/DisplayTable.cshtml
@{
    // Wind Chill = 35.74 + 0.6215T – 35.75(V^0.16) + 0.4275T(V^0.16)

    // calculate nearest values to muliples of 5
    double currentTemp = Math.Round(ViewBag.Temperature / 5) * 5;
    double currentWindSpeed = Math.Round(ViewBag.WindSpeed / 5) * 5;
}

<h2>Wind Chill Table</h2>
@currentTemp
@currentWindSpeed
<div id="WindChillTable">

    <table>

        <tr>
            <td class="headerCells">(mph)</td>
            @for (var temp = -40; temp <= 40; temp +=5)
            {
                <td class="headerCells">@temp&deg;</td>
            }
        </tr>

        @for(var windSpeed = 0; windSpeed <= 50; windSpeed +=5)
        {
        <tr>
            <td class="headerCells">@windSpeed</td>
            @for (var temp = -40; temp <= 40; temp += 5)
            {
                var windChill = 35.74 + (0.6215 * temp) - 35.75 * Math.Pow(windSpeed, 0.16) + 0.4275 * temp * Math.Pow(windSpeed, 0.16);
                windChill = Math.Round(windChill, 0);
                if (temp == currentTemp && windSpeed == currentWindSpeed)
                {
                    <td class="contentCells" style="background-color:red; color:white;">@windChill</td>
                }
                else
                {
                    <td class="contentCells">@windChill</td>
                }

            }
        </tr>
        }

    </table>

</div>

CA_ATaleOfThreeCalculators/Views/TableGenerator/Index.cshtml
<h2>Wind Chill Table Generator</h2>

<form action="TableGenerator/Index" method="Post"  id="CalculatorInputForm">

    <div class="form-group">
        <label for="temperature">Enter the current temperature:</label>
        <input type="text" name="temperature" class="form-control" />
    </div>

    <div class="form-group">
        <label for="windSpeed">Enter the current wind speed:</label>
        <input type="text" name="windSpeed" class="form-control" />
    </div>

    <div class="form-group">
        <input type="submit" name="submit" value="Display Table" class="btn btn-default" />
    </div>

</form>

CA_ATaleOfThreeCalculators/Views/UrlCalculator/Add.cshtml
<h2>Calculate</h2>

<div id="CalculatorOutput">

    @if (ViewBag.answer != null)
    {
    <p>Answer = @ViewBag.answer</p>
    }
    else
    {
    foreach(string errorMessageLine in @ViewBag.errorMessage)
    {
    <p>@errorMessageLine</p>
    }
    }

    @Html.ActionLink("Try Again", "Index", "UrlCalculator", null, new { @class = "btn btn-default" })

</div>

CA_ATaleOfThreeCalculators/Views/UrlCalculator/Index.cshtml
@{
    ViewBag.Title = "URL Calculator";
}

<h2>URL Calculator</h2>

<div id="CalculatorInputForm">

    <div class="form-group">
        <label for="operand1">Enter the first operand:</label>
        <input type="text" name="operand1" id="operand1" class="form-control" />
    </div>

    <div class="form-group">
        <label for="operand2">Enter the second operand:</label>
        <input type="text" name="operand2" id="operand2" class="form-control" />
    </div>

    <div class="form-group">
        <label for="operation">Choose the operation:</label>
        <select name="operation" id="operation" class="form-control">
            <option value="add">Add</option>
            <option value="subtract">Subtract</option>
            <option value="multiply">Multiply</option>
            <option value="divide">Divide</option>
        </select>
    </div>

    <div class="form-group">
        <a href="#" onclick="this.href = 'UrlCalculator/' + document.getElementById('operation').value + '/' + document.getElementById('operand1').value + '/' + document.getElementById('operand2').value" target="_self" class="btn btn-default">Calculate</a>
    </div>

</div>